version: '3'
services:
  db:
    image: mysql
    container_name: mysql-database
    ports: 
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data/init.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=tarpaulin_db
      - MYSQL_USER=tarpaulin_db
      - MYSQL_PASSWORD=password
    networks:
      - mysql-network
networks:
  mysql-network:
    driver: bridge