version: '3'
services:
  api:
    container_name: api
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    ports:
      - "8080:8080"
    networks:
      - mysql-redis-network
    depends_on:
      - db
      - cache
  db:
    image: mysql
    container_name: tarpaulin_db
    ports: 
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data/init.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - mysql-redis-network
  cache:
    image: redis
    container_name: rate-limiting
    ports:
      - "6379:6379"
    networks:
      - mysql-redis-network
networks:
  mysql-redis-network:
    driver: bridge